name: tambola_frontend
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  from_css_color: ^2.0.0
  http: ^0.13.5
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  socket_io_client: ^2.0.0
  google_sign_in: ^5.4.0
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  simple_gradient_text: ^1.2.3
  flutter_switch: ^0.3.2
  timer_count_down: ^2.2.1
  flutter_screenutil: ^5.5.4
  video_player: ^2.4.7
  material_design_icons_flutter: ^3.4.4595
  vdocipher_flutter: ^1.0.0-beta.7
  chewie: ^1.3.5
  get: ^4.6.5
  get_storage: ^2.0.3
  audioplayers: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tbm.png"
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family: IrishGrover
      fonts:
        - asset: fonts/IrishGrover-Regular.ttf

    - family: Inter
      fonts:
        - asset: fonts/Inter-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
